client: "1"
dependencies:
  - --index-url https://pypi.org/simple
  - -r "/Workspace/Users/matthew.giglia@databricks.com/FHIRWorksDLT/requirements.txt"
  - git+https://github.com/databrickslabs/dbignite.git